// Generated by gencpp from file ucar_commander/nav_startRequest.msg
// DO NOT EDIT!


#ifndef UCAR_COMMANDER_MESSAGE_NAV_STARTREQUEST_H
#define UCAR_COMMANDER_MESSAGE_NAV_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_commander
{
template <class ContainerAllocator>
struct nav_startRequest_
{
  typedef nav_startRequest_<ContainerAllocator> Type;

  nav_startRequest_()
    : data(0)  {
    }
  nav_startRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ucar_commander::nav_startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_commander::nav_startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nav_startRequest_

typedef ::ucar_commander::nav_startRequest_<std::allocator<void> > nav_startRequest;

typedef boost::shared_ptr< ::ucar_commander::nav_startRequest > nav_startRequestPtr;
typedef boost::shared_ptr< ::ucar_commander::nav_startRequest const> nav_startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_commander::nav_startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_commander::nav_startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_commander::nav_startRequest_<ContainerAllocator1> & lhs, const ::ucar_commander::nav_startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_commander::nav_startRequest_<ContainerAllocator1> & lhs, const ::ucar_commander::nav_startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_commander::nav_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_commander::nav_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_commander::nav_startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::ucar_commander::nav_startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_commander/nav_startRequest";
  }

  static const char* value(const ::ucar_commander::nav_startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"int8 data\n"
;
  }

  static const char* value(const ::ucar_commander::nav_startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_commander::nav_startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_commander::nav_startRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_COMMANDER_MESSAGE_NAV_STARTREQUEST_H
