// Generated by gencpp from file ucar_commander/nav_startResponse.msg
// DO NOT EDIT!


#ifndef UCAR_COMMANDER_MESSAGE_NAV_STARTRESPONSE_H
#define UCAR_COMMANDER_MESSAGE_NAV_STARTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_commander
{
template <class ContainerAllocator>
struct nav_startResponse_
{
  typedef nav_startResponse_<ContainerAllocator> Type;

  nav_startResponse_()
    : success(false)
    , message()  {
    }
  nav_startResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ucar_commander::nav_startResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_commander::nav_startResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nav_startResponse_

typedef ::ucar_commander::nav_startResponse_<std::allocator<void> > nav_startResponse;

typedef boost::shared_ptr< ::ucar_commander::nav_startResponse > nav_startResponsePtr;
typedef boost::shared_ptr< ::ucar_commander::nav_startResponse const> nav_startResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_commander::nav_startResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_commander::nav_startResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_commander::nav_startResponse_<ContainerAllocator1> & lhs, const ::ucar_commander::nav_startResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_commander::nav_startResponse_<ContainerAllocator1> & lhs, const ::ucar_commander::nav_startResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_commander::nav_startResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_commander::nav_startResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_commander::nav_startResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::ucar_commander::nav_startResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_commander/nav_startResponse";
  }

  static const char* value(const ::ucar_commander::nav_startResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"bool success\n"
"string message\n"
;
  }

  static const char* value(const ::ucar_commander::nav_startResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_startResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_commander::nav_startResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_commander::nav_startResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_COMMANDER_MESSAGE_NAV_STARTRESPONSE_H
