// Generated by gencpp from file ucar_commander/nav_start.msg
// DO NOT EDIT!


#ifndef UCAR_COMMANDER_MESSAGE_NAV_START_H
#define UCAR_COMMANDER_MESSAGE_NAV_START_H

#include <ros/service_traits.h>


#include <ucar_commander/nav_startRequest.h>
#include <ucar_commander/nav_startResponse.h>


namespace ucar_commander
{

struct nav_start
{

typedef nav_startRequest Request;
typedef nav_startResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_start
} // namespace ucar_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_commander::nav_start > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::ucar_commander::nav_start&) { return value(); }
};

template<>
struct DataType< ::ucar_commander::nav_start > {
  static const char* value()
  {
    return "ucar_commander/nav_start";
  }

  static const char* value(const ::ucar_commander::nav_start&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_commander::nav_startRequest> should match
// service_traits::MD5Sum< ::ucar_commander::nav_start >
template<>
struct MD5Sum< ::ucar_commander::nav_startRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_commander::nav_start >::value();
  }
  static const char* value(const ::ucar_commander::nav_startRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_commander::nav_startRequest> should match
// service_traits::DataType< ::ucar_commander::nav_start >
template<>
struct DataType< ::ucar_commander::nav_startRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_commander::nav_start >::value();
  }
  static const char* value(const ::ucar_commander::nav_startRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_commander::nav_startResponse> should match
// service_traits::MD5Sum< ::ucar_commander::nav_start >
template<>
struct MD5Sum< ::ucar_commander::nav_startResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_commander::nav_start >::value();
  }
  static const char* value(const ::ucar_commander::nav_startResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_commander::nav_startResponse> should match
// service_traits::DataType< ::ucar_commander::nav_start >
template<>
struct DataType< ::ucar_commander::nav_startResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_commander::nav_start >::value();
  }
  static const char* value(const ::ucar_commander::nav_startResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_COMMANDER_MESSAGE_NAV_START_H
